apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fastapi-role
  namespace: fastapi-app
rules: [] # No rules, so no permissions are granted

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fastapi-rolebinding
  namespace: fastapi-app
subjects:
  - kind: ServiceAccount
    name: fastapi-service-account
    apiGroup: ""
roleRef:
  kind: Role
  name: fastapi-role
  apiGroup: rbac.authorization.k8s.io 









#   apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   name: fastapi-role
#   namespace: fastapi-app
# rules:
#   # Allow reading configmaps and secrets
#   - apiGroups: [""]
#     resources: ["configmaps", "secrets"]
#     verbs: ["get", "list", "watch"]
  
#   # Allow service discovery
#   - apiGroups: [""]
#     resources: ["services", "endpoints"]
#     verbs: ["get", "list", "watch"]
  
#   # Allow reading pod information (for health checks)
#   - apiGroups: [""]
#     resources: ["pods"]
#     verbs: ["get", "list"]