apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alerts
  namespace: monitoring
data:
  alerts.yml: |
    groups:
      - name: fastapi-alerts
        rules:
          # FastAPI Service Down
          - alert: FastAPIServiceDown
            expr: up{job="fastapi"} == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "FastAPI service is down"
              description: "FastAPI service has been down for more than 1 minute"

          # High Response Time
          - alert: HighResponseTime
            expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: "High response time for FastAPI"
              description: "95th percentile response time is above 1 second"

          # High Request Rate
          - alert: HighRequestRate
            expr: rate(http_requests_total[5m]) > 100
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: "High request rate for FastAPI"
              description: "Request rate is above 100 requests per second"

      - name: system-alerts
        rules:
          # High CPU Usage
          - alert: HighCPUUsage
            expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: "High CPU usage on {{ $labels.instance }}"
              description: "CPU usage is above 80% for more than 2 minutes"

          # High Memory Usage
          - alert: HighMemoryUsage
            expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: "High memory usage on {{ $labels.instance }}"
              description: "Memory usage is above 85% for more than 2 minutes"

          # High Disk Usage
          - alert: HighDiskUsage
            expr: (node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes * 100 > 90
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: "High disk usage on {{ $labels.instance }}"
              description: "Disk usage is above 90% for more than 2 minutes" 