#  Deny all ingress by default, Block all incoming traffic by default. network policies implements zero trust networking. 
# network policies allows to define which pods or ns can send traffic to other pods. allows us to define only the traffic we need. 
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: fastapi-app
spec:
  podSelector: {}
  policyTypes:
    - Ingress
---
# 2. Allow ingress only from NGINX Ingress Controller to FastAPI
# prevents unauthorized pods from acessing the appliction. 
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-nginx-ingress-to-fastapi
  namespace: fastapi-app
spec:
  podSelector:
    matchLabels:
      app: fastapi-deployment  
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
          podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
