# provide identity for pods to authenticate with the kubernetes API and ensures pods only gets the permissions they need. 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fastapi-service-account
  namespace: fastapi-app