apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      # nodePort: 30010
  type: ClusterIP